#!%%BASH_SHEBANG%%
#
# ExaWind build script for project: %%PROJECT%%
#
# Autogenerated for %%SYSTEM%% and %%COMPILER%%
#
# 1. See https://exawind-builder.readthedocs.io for documentation
# 2. Use new-script.sh to regenerate this script
#

#
# Setup variables used by functions
#
export EXAWIND_SRCDIR=%%SRCDIR%%
export EXAWIND_COMPILER=%%COMPILER%%
export EXAWIND_SYSTEM=%%SYSTEM%%
export EXAWIND_CODE=%%PROJECT%%
export EXAWIND_CFGFILE=exawind-config

#
# Source the core, system, and project specific build scripts
#
source ${EXAWIND_SRCDIR}/core.bash
source ${EXAWIND_SRCDIR}/envs/${EXAWIND_SYSTEM}.bash
source ${EXAWIND_SRCDIR}/codes/${EXAWIND_CODE}.bash

# Path to ExaWind project and install directories
export EXAWIND_PROJECT_DIR=${EXAWIND_PROJECT_DIR:-%%EXAWIND_PRJDIR%%}
export EXAWIND_INSTALL_DIR=${EXAWIND_INSTALL_DIR:-${EXAWIND_PROJECT_DIR}/install/${EXAWIND_COMPILER}}
export EXAWIND_CONFIG=${EXAWIND_CONFIG:-${EXAWIND_PROJECT_DIR}/${EXAWIND_CFGFILE}.sh}

# Source any user specific configuration (see documentation)
exawind_load_user_configs

# Path to the source directory (absolute or relative to build directory)
%%CODE_DIR%%=${%%CODE_DIR%%:-..}
# Path where `make install` will install files for this project
%%INSTALL_DIR%%=${%%INSTALL_DIR%%:-${EXAWIND_INSTALL_DIR}/%%PROJECT%%}

########## BEGIN user specific configuration ###########

########## END user specific configuration   ###########

### Execute main function (must be last line of this script)
if [[ "${BASH_SOURCE[0]}" != "${0}" ]] ; then
    exawind_env && exawind_proj_env
else
    exawind_main "$@"
fi
