#!/usr/bin/env bash
#
# ExaWind build script for project: {{ project }}
#
# Autogenerated for {{ system }} and {{ compiler }}
#
# 1. See https://exawind.github.io/exawind-builder for documentation
# 2. Use new-script.sh to regenerate this script
#

{% set source_dir_var = project.upper().replace('-', '_') + "_SOURCE_DIR" %}
{% set install_dir_var = project.upper().replace('-', '_') + "_INSTALL_PREFIX" -%}

#
# Setup variables used by functions
#
export EXAWIND_SRCDIR={{ exawind_builder_dir }}
export EXAWIND_COMPILER={{ compiler }}
export EXAWIND_SYSTEM={{ system }}
export EXAWIND_CODE={{ project }}
export EXAWIND_CFGFILE=exawind-config
export EXAWIND_PROJECT_DIR=${EXAWIND_PROJECT_DIR:-$(dirname ${EXAWIND_SRCDIR})}

#
# Source the core, system, and project specific build scripts
#
source ${EXAWIND_SRCDIR}/core.bash
source ${EXAWIND_SRCDIR}/envs/${EXAWIND_SYSTEM}.bash
source ${EXAWIND_SRCDIR}/codes/${EXAWIND_CODE}.bash

# Path to ExaWind project and install directories
export EXAWIND_PROJECT_DIR=${EXAWIND_PROJECT_DIR:-{{ exawind_dir }}}
export EXAWIND_INSTALL_DIR=${EXAWIND_INSTALL_DIR:-${EXAWIND_PROJECT_DIR}/install/${EXAWIND_COMPILER}}
export EXAWIND_CONFIG=${EXAWIND_CONFIG:-${EXAWIND_PROJECT_DIR}/${EXAWIND_CFGFILE}.sh}

# Source any user specific configuration (see documentation)
exawind_load_user_configs

{{ source_dir_var }}=${ {{- source_dir_var -}} :-..}
{{ install_dir_var }}=${ {{- install_dir_var -}} :-${EXAWIND_INSTALL_DIR}/ {{- project -}} }

exawind_main "$@"
