# Bootstrap script to get all brew packages installed for exawind-builder
#
# To install:
#
# brew bundle --file=<PATH_TO_THIS_FILE>
#

brew "bash"
brew "cmake"
brew "gcc"
brew "autoconf"
brew "automake"
brew "fftw"
brew "pkg-config"
brew "modules"

