name: docs

on:
  push:
    branches: [master]
    paths:
       - 'doc/**'
       - '.github/workflows/docs.yml'
  pull_request:
    branches: [master]
    paths:
       - 'doc/**'
       - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
      - name: Build
        working-directory: ${{github.workspace}}/doc
        run: |
           make html
           touch ${{github.workspace}}/doc/build/html/.nojekyll
      - name: Deploy
        # Only deploy on push to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: ${{github.workspace}}/doc/build/html
          SINGLE_COMMIT: true
